name: pr-agent
on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited, synchronize]
    
permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    steps:
    - name: Switch to pull request branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Count lines and files
      id: count
      run: |
        git fetch origin ${base_branch}:${base_branch}
        echo ${{ github.event.pull_request.user.login }}
        echo "${{ github.event.pull_request.base.sha }}"
        echo "${{ github.event.pull_request.head.sha }}"
        line_count=$(git diff --shortstat ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | awk '{print $4}')
        echo "$line_count"
        echo "line_count=$line_count" >> $GITHUB_OUTPUT

    - name: Run PR Agent
      if: ${{ github.event.pull_request.user.login == 'taka-hattori' && steps.count.outputs.line_count < 20 && steps.count.outputs.line_count > 0}}
      id: pr-agent
      uses: Codium-ai/pr-agent@main
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG.MODEL: 'gpt-3.5-turbo-16k'
        PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese'
        PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese'
