name: pr-agent
on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    steps:
    - name: Count lines and files
      id: count
      run: |
        file_count=${{ steps.pr-changes.outputs.count }}
        line_count=$(git diff --shortstat ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | awk '{print $4}')
        echo "$file_count $line_count"
        echo "${{ github.event.pull_request.user.login }}"
        echo "file_count=$file_count" >> $GITHUB_OUTPUT
        echo "line_count=$line_count" >> $GITHUB_OUTPUT

    - name: Run PR Agent
      if: ${{ github.event.pull_request.user.login == 'taka-hattori' && steps.count.outputs.line_count < 1000 && steps.count.outputs.file_count < 10 }}
      id: pr-agent
      uses: Codium-ai/pr-agent@main
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG.MODEL: 'gpt-3.5-turbo-16k'
        PR_REVIEWER.EXTRA_INSTRUCTIONS: '日本語で回答をお願いします。'
        PR_DESCRIPTION.EXTRA_INSTRUCTIONS: '日本語で回答をお願いします。'
