name: pr-agent
on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    if: contains('taka-hattori,disc99', github.event.pull_request.user.login)
    steps:
    - name: Switch to pull request branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Count lines and files
      id: count
      run: |
        git fetch origin ${github.base_ref}:${github.base_ref}
        line_count=$(git diff --shortstat ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | awk '{print $4+$6}')
        echo "line_count=$line_count" >> $GITHUB_OUTPUT
